routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Attribute;

use App\helper\ClearStream;
use App\Streamer;


Route::get('/', function () {


    $attributes = Attribute::first();
    $locale = app()->getLocale();
    $all = Streamer::all();

    if ($all->isEmpty()) {
        $first = 0;
    } else {

        if (Streamer::count() < 4) {
            $first = Streamer::latest()->first()->id;
        } else {
            $first = $all->first()->id;
        }

    }


    return redirect('home/en/' . $first)->with($locale, $attributes);
});

Route::get('/home', function () {
    $attributes = Attribute::first();
    $locale = app()->getLocale();
    $all = Streamer::all();

    if ($all->isEmpty()) {
        $first = 0;
    } else {

        if (Streamer::count() < 4) {
            $first = Streamer::latest()->first()->id;
        } else {
            $first = $all->first()->id;
        }

    }

    return redirect('home/en/' . $first)->with($locale, $attributes);
});

Route::get('/home/en', function () {
    $attributes = Attribute::first();
    $locale = app()->getLocale();
    $all = Streamer::all();

    if ($all->isEmpty()) {
        $first = 0;
    } else {

        if (Streamer::count() < 4) {

            $first = Streamer::latest()->first()->id;

        } else {
            $first = $all->first()->id;
        }

    }

    return redirect('home/en/' . $first)->with($locale, $attributes);
});

Route::get('/admin', function () {
    $attributes = Attribute::first();
    $locale = app()->getLocale();
    return redirect('admin/en')->with($locale, $attributes);
});


Auth::routes(['register' => false]);


Route::get('/home/{locale}/{forID}', 'HomeController@index')->name('home');
Route::get('/portfolio/{locale}', 'HomeController@portfolio')->name('portfolio');
Route::get('/about/{locale}', 'HomeController@about')->name('about');
Route::get('/contact/{locale}', 'HomeController@contact')->name('contact');


Route::get('createTranslate', 'HomeController@createTranslate')->name('createTranslate');


Route::post('destroyAll', 'adminControllers\ContactController@destroyAll')->name('destroyAll');


Route::middleware('auth')->prefix('admin/{locale}')->group(function () {


    Route::get('/', 'adminControllers\AdminController@index')->name('dashboard');

    Route::resource('category', 'adminControllers\CategoryController');
    Route::resource('sub-category', 'adminControllers\SubCategoryController');
    Route::resource('product', 'adminControllers\ProductController');
    Route::resource('attribute', 'adminControllers\AttributeController');
    Route::resource('contact', 'adminControllers\ContactController');
    Route::resource('image', 'adminControllers\ImageController');
    Route::resource('about', 'adminControllers\AboutController');
    Route::resource('info', 'adminControllers\InfoController');
    Route::resource('slide', 'adminControllers\SlideController');
    Route::resource('partner', 'adminControllers\PartnerController');

});


Route::get('/content/{locale}', 'HomeController@content')->name('content');
Route::post('/search/{locale}', 'HomeController@search')->name('search');
Route::post('/stream', 'HomeController@stream')->name('stream');
Route::get('/show/{locale}/{id}', 'HomeController@show')->name('show');
Route::get('/streaming/{locale}/{id}', 'HomeController@streaming')->name('streaming');
Route::get('/policy', 'HomeController@policy')->name('policy');
Route::get('/home/en/cleanStreams', 'HomeController@cleanStreams')->name('cleanStreams');
Route::get('/children', 'HomeController@children')->name('children');
Route::get('/info', 'HomeController@info')->name('info');
Route::get('/creature', 'HomeController@creature')->name('creature');
Route::get('/works', 'HomeController@works')->name('works');
Route::get('/testpage/{locale}/{id}', 'HomeController@testpage')->name('testpage');
Route::post('/jsDeleteStream/{id}', 'HomeController@jsDeleteStream')->name('jsDeleteStream');
Route::post('/checkIp', 'HomeController@checkIp')->name('checkIp');


Route::get('/testpage', function () {


    $attributes = Attribute::first();
    $locale = app()->getLocale();
    $all = Streamer::all();

    if ($all->isEmpty()) {
        $first = 0;
    } else {
        $first = $all->first()->id;
    }


    return redirect('testpage/en/' . $first)->with($locale, $attributes);
});

Route::get('/testpage/en', function () {
    $attributes = Attribute::first();
    $locale = app()->getLocale();
    $all = Streamer::all();

    if ($all->isEmpty()) {
        $first = 0;
    } else {
        $first = $all->first()->id;
    }

    return redirect('testpage/en/' . $first)->with($locale, $attributes);
});

app/SubCategory.php
<?php

namespace App;

use Astrotomic\Translatable\Contracts\Translatable as TranslatableContract;
use Astrotomic\Translatable\Translatable;
use Illuminate\Database\Eloquent\Model;
use Laravel\Scout\Searchable;


class SubCategory extends Model implements TranslatableContract
{
    use Translatable, Searchable;

    protected $table = 'sub_categories';
    public $translatedAttributes = ['name'];

    protected $guarded = [];

    public function toSearchableArray()
    {
        $data = $this->toArray();
        $data['products'] = $this->products->toArray();
        return $data;
    }



    public function products()
    {
        return $this->hasMany(Product::class)->orderBy('created_at', 'desc');
    }

}

app/Http/Controllers/adminControllers/SubCategoryController.php
<?php

namespace App\Http\Controllers\adminControllers;

use App\Attribute;
use App\Category;
use App\Http\Controllers\Controller;
use App\SubCategory;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\App;

class SubCategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index($locale)
    {

        $attributes = Attribute::first();
        $id = request('id');
        $category = Category::find($id);
        $SubCategories = SubCategory::all()->where('category_id',$id );
        return view('admin.sub-category.index', compact('SubCategories','category', 'locale','attributes'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $locale = request('locale');
        $id = request('id');

        $subCategoryen = request('subCategoryen');
        $subCategoryka = request('subCategoryka');

        $data = [
            'category_id' => $id,
            'name' => 'sub',
            'en' => ['name' => $subCategoryen],
            'ka' => ['name' => $subCategoryka],
        ];

        SubCategory::create($data);


        return back();


    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($locale , $id)
    {

        $attributes = Attribute::first();
        App::setLocale($locale);
        $subCategory = SubCategory::find($id);
        return view('admin.sub-category.edit', compact('subCategory','locale','attributes'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $locale, $id)
    {
        $subCategoryen = request('subcategoryen');
        $subCategoryka = request('subcategoryka');

        $subCategory = SubCategory::find($id);

        $subCategory->translate('en')->name = $subCategoryen;
        $subCategory->translate('ka')->name = $subCategoryka;
        $subCategory->save();


        return redirect('admin/'.$locale.'/sub-category?id='.$id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($locale, $id)
    {
        SubCategory::find($id)->delete();

        return back();
    }
}

resources/views/admin/sub-category/edit.blade.php
@extends('admin.layouts.app')
@section('content')
@include('admin.layouts.header')
<form action="{{ route('sub-category.update', [$locale, $subCategory->id]) }}" method="post">
    @csrf
    @method('patch')
    <div class="container mt-3">

        <label class=" no-border">{{ $attributes->translate($locale)->edit_sub_category }}</label>
        <input class="form-control " name="subcategoryen" value="{{ $subCategory->translate('en')->name }}">
        <input class="form-control mt-2"  name="subcategoryka" value="{{ $subCategory->translate('ka')->name }}">

        <button type="submit" class="btn btn-warning mt-2">{{ $attributes->translate($locale)->edit }}</button>

    </div>
</form>
@include('admin.layouts.footer')
@endsection

resources/views/admin/sub-category/index.blade.php
@extends('admin.layouts.app')
@section('content')
    @include('admin.layouts.header')

    @if($errors->all())
        <div class="notification error closeable">
            @foreach ($errors->all() as $error)
                <p>{{ $error }}</p>
            @endforeach
            <a class="close"></a>
        </div>
    @endif


    <form id="subCategoryStore" action="{{ route('sub-category.store', ['locale' => $locale, 'id' => $category->id]) }}"
          method="post">
        @csrf
        <div class="container mt-3">

            <div class="col-8">
                <input value="{{ $category->id }}" name="mainCategoryId" hidden>
                <label>{{ $category->translate($locale)->name }}</label>

            </div>
            <div class="col-8 row">
                <div class="col-1">
                </div>
                <div class="col-8">
                    <label class="mt-4">{{ $attributes->translate($locale)->edit_sub_category }} : {{ $category->translate($locale)->name }}</label>

                    <input name="subCategoryen" class="form-control col-" placeholder="English">
                    <input name="subCategoryka" class="form-control mt-2" placeholder="ქართულად">

                    <button onclick="document.getElementById('subCategoryStore').submit();"
                            class="btn btn-primary mt-2" type="submit">{{ $attributes->translate($locale)->create }}
                    </button>

                </div>

            </div>


        </div>

    </form>

    <div class="container mt-3">


        <div class="container">
            <div class="card">
                <div class="card-header">
                    <span class="card-title">{{ $attributes->translate($locale)->sub_categories }}</span>
                </div>

                <div class="table-stats order-table ">
                    <table class="table">
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>{{ $attributes->translate($locale)->name }}</th>
                            <th>{{ $attributes->translate($locale)->createdAt }}</th>
                            <th></th>
                        </tr>
                        </thead>
                        @foreach($SubCategories as $SubCategory)

                            <form method="post" action="{{ route('sub-category.destroy',[  $locale, $SubCategory->id]) }}">
                                @csrf
                                {{ method_field('delete') }}
                                <tbody>
                                <tr>
                                    <td>{{ $SubCategory->id }}</td>
                                    <td>{{ $SubCategory->translate($locale)->name}}</td>
                                    <td>{{ $SubCategory->created_at}}</td>
                                    <td class="row pull-right mr-2">
                                        <a href="{{ route('sub-category.edit', [ $locale, $SubCategory->id]) }}"
                                           class="btn btn-sm btn-warning mr-1">{{ $attributes->translate($locale)->edit }}</a>
                                        <button type="submit"
                                                class="btn btn-sm btn-danger delete">{{ $attributes->translate($locale)->delete }}
                                        </button>
                                    </td>
                                </tr>
                                </tbody>
                            </form>
                        @endforeach
                    </table>
                </div>


            </div>

        </div>


    </div>

    @include('admin.layouts.footer')
@endsection