routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Attribute;

use App\helper\ClearStream;
use App\Streamer;


Route::get('/', function () {


    $attributes = Attribute::first();
    $locale = app()->getLocale();
    $all = Streamer::all();

    if ($all->isEmpty()) {
        $first = 0;
    } else {

        if (Streamer::count() < 4) {
            $first = Streamer::latest()->first()->id;
        } else {
            $first = $all->first()->id;
        }

    }


    return redirect('home/en/' . $first)->with($locale, $attributes);
});

Route::get('/home', function () {
    $attributes = Attribute::first();
    $locale = app()->getLocale();
    $all = Streamer::all();

    if ($all->isEmpty()) {
        $first = 0;
    } else {

        if (Streamer::count() < 4) {
            $first = Streamer::latest()->first()->id;
        } else {
            $first = $all->first()->id;
        }

    }

    return redirect('home/en/' . $first)->with($locale, $attributes);
});

Route::get('/home/en', function () {
    $attributes = Attribute::first();
    $locale = app()->getLocale();
    $all = Streamer::all();

    if ($all->isEmpty()) {
        $first = 0;
    } else {

        if (Streamer::count() < 4) {

            $first = Streamer::latest()->first()->id;

        } else {
            $first = $all->first()->id;
        }

    }

    return redirect('home/en/' . $first)->with($locale, $attributes);
});

Route::get('/admin', function () {
    $attributes = Attribute::first();
    $locale = app()->getLocale();
    return redirect('admin/en')->with($locale, $attributes);
});


Auth::routes(['register' => false]);


Route::get('/home/{locale}/{forID}', 'HomeController@index')->name('home');
Route::get('/portfolio/{locale}', 'HomeController@portfolio')->name('portfolio');
Route::get('/about/{locale}', 'HomeController@about')->name('about');
Route::get('/contact/{locale}', 'HomeController@contact')->name('contact');


Route::get('createTranslate', 'HomeController@createTranslate')->name('createTranslate');


Route::post('destroyAll', 'adminControllers\ContactController@destroyAll')->name('destroyAll');


Route::middleware('auth')->prefix('admin/{locale}')->group(function () {


    Route::get('/', 'adminControllers\AdminController@index')->name('dashboard');

    Route::resource('category', 'adminControllers\CategoryController');
    Route::resource('sub-category', 'adminControllers\SubCategoryController');
    Route::resource('product', 'adminControllers\ProductController');
    Route::resource('attribute', 'adminControllers\AttributeController');
    Route::resource('contact', 'adminControllers\ContactController');
    Route::resource('image', 'adminControllers\ImageController');
    Route::resource('about', 'adminControllers\AboutController');
    Route::resource('info', 'adminControllers\InfoController');
    Route::resource('slide', 'adminControllers\SlideController');
    Route::resource('partner', 'adminControllers\PartnerController');

});


Route::get('/content/{locale}', 'HomeController@content')->name('content');
Route::post('/search/{locale}', 'HomeController@search')->name('search');
Route::post('/stream', 'HomeController@stream')->name('stream');
Route::get('/show/{locale}/{id}', 'HomeController@show')->name('show');
Route::get('/streaming/{locale}/{id}', 'HomeController@streaming')->name('streaming');
Route::get('/policy', 'HomeController@policy')->name('policy');
Route::get('/home/en/cleanStreams', 'HomeController@cleanStreams')->name('cleanStreams');
Route::get('/children', 'HomeController@children')->name('children');
Route::get('/info', 'HomeController@info')->name('info');
Route::get('/creature', 'HomeController@creature')->name('creature');
Route::get('/works', 'HomeController@works')->name('works');
Route::get('/testpage/{locale}/{id}', 'HomeController@testpage')->name('testpage');
Route::post('/jsDeleteStream/{id}', 'HomeController@jsDeleteStream')->name('jsDeleteStream');
Route::post('/checkIp', 'HomeController@checkIp')->name('checkIp');


Route::get('/testpage', function () {


    $attributes = Attribute::first();
    $locale = app()->getLocale();
    $all = Streamer::all();

    if ($all->isEmpty()) {
        $first = 0;
    } else {
        $first = $all->first()->id;
    }


    return redirect('testpage/en/' . $first)->with($locale, $attributes);
});

Route::get('/testpage/en', function () {
    $attributes = Attribute::first();
    $locale = app()->getLocale();
    $all = Streamer::all();

    if ($all->isEmpty()) {
        $first = 0;
    } else {
        $first = $all->first()->id;
    }

    return redirect('testpage/en/' . $first)->with($locale, $attributes);
});

app/Partners.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Partners extends Model
{
    protected $guarded = [];

    protected $table = 'partners';
}

app/Http/Controllers/adminControllers/PartnerController.php
<?php

namespace App\Http\Controllers\adminControllers;

use App\Attribute;
use App\Http\Controllers\Controller;
use App\Partners;
use App\Slides;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\App;

class PartnerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index($locale)
    {
        App::setLocale($locale);

        $partners = Partners::all();
        $attribute = Attribute::first();
        return view('admin.partner.index', compact('attribute', 'locale', 'partners'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, $locale)
    {
        $this->validate($request, [

            'image' => 'required|mimes:jpeg,png,jpg,svg|max:2048',
        ]);

        $pluss = random_int(1,255);
        $date = Carbon::now()->format('Y-m-d-h-m-s');
        $imageName = $date . '.' . $pluss . $request->image->getClientOriginalExtension();
        $request->image->move(public_path('/images/partners'), $imageName);

        $data = [
            'info_id' => 1,
            'image' => $imageName,
        ];

        Partners::create($data);

        return back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($locale, $id)
    {
        Partners::find($id)->delete();
        return back();
    }
}

resources/views/admin/partner/index.blade.php
@extends('admin.layouts.app')
@section('content')
    @include('admin.layouts.header')

    @if($errors->all())
        <div class="notification error closeable">
            @foreach ($errors->all() as $error)
                <p>{{ $error }}</p>
            @endforeach
            <a class="close"></a>
        </div>
    @endif
    <form action="{{ route('partner.store', $locale) }}" method="POST" enctype="multipart/form-data">
        @csrf
        <label class="form-control-label mt-4 mb-3 ml-3 text-bold">Upload Partner</label>
        <div class="container mt-5">
            <div class="col-">
                <div class="container border">
                    <div class="input-group mb-2 mt-2">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="inputGroupFileAddon01">Upload</span>
                        </div>
                        <div class="custom-file">
                            <input name="image" type="file" class="custom-file-input" id="inputGroupFile01"
                                   aria-describedby="inputGroupFileAddon01">
                            <label class="custom-file-label" for="inputGroupFile01">Choose file</label>
                        </div>
                    </div>
                </div>

                <button class="btn btn-primary mt-4" type="submit">Upload</button>
            </div>
        </div>
    </form>


    <p class="form-control-plaintext ml-5 text-center text-bold">Partner List</p>

    <div class="col-12 row container">
        @foreach($partners as $partner )

            <div class="col-6 pull-right">
                <form action="{{route('partner.destroy', [  $locale, $partner->id ?? '']) }}" method="post" class="mb-5">
                    @csrf
                    @method('delete')
                    <div class="container border">
                        <button class="btn btn-danger pull-right"
                                onclick="document.getElementById('remove-image').submit();">Remove
                        </button>
                        <img class="profile-pic" src="/images/partners/{{ $partner->image }}"/>
                    </div>
                </form>
            </div>

        @endforeach
    </div>

    <form id="remove-image" action="{{ route('partner.destroy', [  $locale, $partner->id ?? '' ] ) }}" method="post">
        @csrf
        @method('delete')
    </form>

    @include('admin.layouts.footer')
@endsection