routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Attribute;

use App\helper\ClearStream;
use App\Streamer;


Route::get('/', function () {


    $attributes = Attribute::first();
    $locale = app()->getLocale();
    $all = Streamer::all();

    if ($all->isEmpty()) {
        $first = 0;
    } else {

        if (Streamer::count() < 4) {
            $first = Streamer::latest()->first()->id;
        } else {
            $first = $all->first()->id;
        }

    }


    return redirect('home/en/' . $first)->with($locale, $attributes);
});

Route::get('/home', function () {
    $attributes = Attribute::first();
    $locale = app()->getLocale();
    $all = Streamer::all();

    if ($all->isEmpty()) {
        $first = 0;
    } else {

        if (Streamer::count() < 4) {
            $first = Streamer::latest()->first()->id;
        } else {
            $first = $all->first()->id;
        }

    }

    return redirect('home/en/' . $first)->with($locale, $attributes);
});

Route::get('/home/en', function () {
    $attributes = Attribute::first();
    $locale = app()->getLocale();
    $all = Streamer::all();

    if ($all->isEmpty()) {
        $first = 0;
    } else {

        if (Streamer::count() < 4) {

            $first = Streamer::latest()->first()->id;

        } else {
            $first = $all->first()->id;
        }

    }

    return redirect('home/en/' . $first)->with($locale, $attributes);
});

Route::get('/admin', function () {
    $attributes = Attribute::first();
    $locale = app()->getLocale();
    return redirect('admin/en')->with($locale, $attributes);
});


Auth::routes(['register' => false]);


Route::get('/home/{locale}/{forID}', 'HomeController@index')->name('home');
Route::get('/portfolio/{locale}', 'HomeController@portfolio')->name('portfolio');
Route::get('/about/{locale}', 'HomeController@about')->name('about');
Route::get('/contact/{locale}', 'HomeController@contact')->name('contact');


Route::get('createTranslate', 'HomeController@createTranslate')->name('createTranslate');


Route::post('destroyAll', 'adminControllers\ContactController@destroyAll')->name('destroyAll');


Route::middleware('auth')->prefix('admin/{locale}')->group(function () {


    Route::get('/', 'adminControllers\AdminController@index')->name('dashboard');

    Route::resource('category', 'adminControllers\CategoryController');
    Route::resource('sub-category', 'adminControllers\SubCategoryController');
    Route::resource('product', 'adminControllers\ProductController');
    Route::resource('attribute', 'adminControllers\AttributeController');
    Route::resource('contact', 'adminControllers\ContactController');
    Route::resource('image', 'adminControllers\ImageController');
    Route::resource('about', 'adminControllers\AboutController');
    Route::resource('info', 'adminControllers\InfoController');
    Route::resource('slide', 'adminControllers\SlideController');
    Route::resource('partner', 'adminControllers\PartnerController');

});


Route::get('/content/{locale}', 'HomeController@content')->name('content');
Route::post('/search/{locale}', 'HomeController@search')->name('search');
Route::post('/stream', 'HomeController@stream')->name('stream');
Route::get('/show/{locale}/{id}', 'HomeController@show')->name('show');
Route::get('/streaming/{locale}/{id}', 'HomeController@streaming')->name('streaming');
Route::get('/policy', 'HomeController@policy')->name('policy');
Route::get('/home/en/cleanStreams', 'HomeController@cleanStreams')->name('cleanStreams');
Route::get('/children', 'HomeController@children')->name('children');
Route::get('/info', 'HomeController@info')->name('info');
Route::get('/creature', 'HomeController@creature')->name('creature');
Route::get('/works', 'HomeController@works')->name('works');
Route::get('/testpage/{locale}/{id}', 'HomeController@testpage')->name('testpage');
Route::post('/jsDeleteStream/{id}', 'HomeController@jsDeleteStream')->name('jsDeleteStream');
Route::post('/checkIp', 'HomeController@checkIp')->name('checkIp');


Route::get('/testpage', function () {


    $attributes = Attribute::first();
    $locale = app()->getLocale();
    $all = Streamer::all();

    if ($all->isEmpty()) {
        $first = 0;
    } else {
        $first = $all->first()->id;
    }


    return redirect('testpage/en/' . $first)->with($locale, $attributes);
});

Route::get('/testpage/en', function () {
    $attributes = Attribute::first();
    $locale = app()->getLocale();
    $all = Streamer::all();

    if ($all->isEmpty()) {
        $first = 0;
    } else {
        $first = $all->first()->id;
    }

    return redirect('testpage/en/' . $first)->with($locale, $attributes);
});

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Astrotomic\Translatable\Contracts\Translatable as TranslatableContract;
use Astrotomic\Translatable\Translatable;
use Laravel\Scout\Searchable;

class Product extends Model implements TranslatableContract
{
    use Translatable;
    use Searchable;


    protected $table = 'products';
    public $translatedAttributes = ['name', 'description', 'style', 'material'];

    protected $guarded = [];

    public function toSearchableArray()
    {
        $data = $this->toArray();
        $data['images'] = $this->images->toArray();
        return $data;
    }


    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function images()
    {
        return $this->hasMany(Image::class);
    }
}

app/Http/Controllers/adminControllers/ProductController.php
<?php

namespace App\Http\Controllers\adminControllers;

use App\Attribute;
use App\Http\Controllers\Controller;
use App\Image;
use App\Product;
use App\SubCategory;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Storage;



class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index($locale)
    {

        $attributes = Attribute::first();
        $products = Product::all();
        App::setLocale($locale);



        return view('admin.product.index', compact('locale', 'products','attributes'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create($locale)
    {

        $attributes = Attribute::first();
        App::setLocale($locale);

        $subCategories = SubCategory::all();

        


        return view('admin.product.create', compact('locale', 'subCategories','attributes'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, $locale)
    {

        $this->validate($request, [
            'productnameen' => 'required|max:255',
            'productnameka' => 'required|max:255',
            'productdescriptionen' => 'required',
            'productdescriptionka' => 'required',
            'productstyleen' => 'required',
            'productstyleka' => 'required',
            'productmaterialen' => 'required',
            'productmaterialka' => 'required',

            'images.*' => 'required|image|mimes:jpeg,png,jpg,svg|max:2048'

        ]);
//        dd(request()->all());

        $id = request('id');
        $productNameEn = request('productnameen');
        $productNameKa = request('productnameka');
        $productDescriptionEn = request('productdescriptionen');
        $productDescriptionKa = request('productdescriptionka');
        $productstyleEn = request('productstyleen');
        $productstyleKa = request('productstyleka');
        $productmaterialEn = request('productmaterialen');
        $productmaterialKa = request('productmaterialka');
        $price = request('price');


        $data = [
            'sub_category_id' => $id,
            'price' => $price,
            'en' => [
                'name' => $productNameEn,
                'description' => $productDescriptionEn,
                'style' => $productstyleEn,
                'material' => $productmaterialEn,
            ],
            'ka' => [
                'name' => $productNameKa,
                'description' => $productDescriptionKa,
                'style' => $productstyleKa,
                'material' => $productmaterialKa,
            ],
        ];

        $product = Product::create($data);

        $date = Carbon::now()->format('Y-m-d-hh-mm-ss');
        $files = request('images');

        $pluss = 1;
        foreach ($files as $file) {
            $imageName = $date . '.' . $pluss . $file->getClientOriginalExtension();
            $file->move(public_path('/images/products'), $imageName);
            $pluss++;

            $data = [
                'image' => $imageName,
                'product_id' => $product->id
            ];

            Image::create($data);


        }


        App::setLocale($locale);

        session()->flash('message', 'პროდუქტი წარმატებით დაემატა');

        return redirect('admin/' . $locale . '/product');


    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($locale, $id)
    {

        $attributes = Attribute::first();
        App::setLocale($locale);
        $product = Product::with('images')->find($id);
        return view('admin.product.edit', compact('product', 'locale','attributes'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $locale, $id)
    {


        $this->validate($request, [
            'productnameen' => 'max:255',
            'productnameka' => 'max:255',
            'productdescriptionen' => 'max:255',
            'productdescriptionka' => 'max:255',
            'productstyleen' => 'max:255',
            'productstyleka' => 'max:255',
            'productmaterialen' => 'max:255',
            'productmaterialka' => 'max:255',
            'images.*' => 'required|image|mimes:jpeg,png,jpg,svg|max:2048'

        ]);

        $product = Product::find($id);

        $productstyleEn = request('productstyleen');
        $productstyleKa = request('productstyleka');
        $productmaterialEn = request('productmaterialen');
        $productmaterialKa = request('productmaterialka');

        if (request('productnameen')) {
            $product->translate('en')->name = request('productnameen');
            $product->save();
        }

        if (request('productnameka')) {
            $product->translate('ka')->name = request('productnameka');
            $product->save();
        }

        if (request('descriptionen')) {
            $product->translate('en')->description = request('descriptionen');
            $product->save();
        }

        if (request('descriptionka')) {
            $product->translate('ka')->description = request('descriptionka');
            $product->save();
        }

        if (request('productstyleen')) {
            $product->translate('en')->style = request('productstyleen');
            $product->save();
        }

        if (request('productstyleka')) {
            $product->translate('ka')->style = request('productstyleka');
            $product->save();
        }

        if (request('productmaterialen')) {
            $product->translate('en')->material = request('productmaterialen');
            $product->save();
        }

        if (request('productmaterialka')) {
            $product->translate('ka')->material = request('productmaterialka');
            $product->save();
        }

        if (request('productprice')) {
            $product->price = request('productprice');
            $product->save();
        }

        if (request('favorite')) {

            ($product->favorite) ? $product->favorite = false : $product->favorite = true;
//            if ($product->favorite == false){
//                $product->favorite = true;
//            } else {
//                $product->favorite = false;
//            }
            $product->save();
        }


        if (request('image')) {
            $date = Carbon::now()->format('Y-m-d-hh-mm-ss');
            $files = request('image');
            $pluss = 1;

            foreach ($files as $file) {
                $imageName = $date . '.' . $pluss . $file->getClientOriginalExtension();
                $file->move(public_path('/images/products'), $imageName);
                $pluss++;

                $data = [
                    'image' => $imageName,
                    'product_id' => $product->id
                ];

                Image::create($data);


            }
        }


        $product->save();
        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($locale, $id)
    {

        $product = Product::find($id);
        Storage::disk('public')->delete("products/" . $product->image);

        session()->flash('message', 'პროდუქტი წარმატებით წაიშალა');

        Product::find($id)->delete();

        return back();
    }
}

resources/views/admin/product/create.blade.php
@extends('admin.layouts.app')
@section('content')
    @include('admin.layouts.header')

    @if($errors->all())
        <div class="notification error closeable">
            @foreach ($errors->all() as $error)
                <p>{{ $error }}</p>
            @endforeach
            <a class="close"></a>
        </div>
    @endif

    <form action="{{ route('product.store', $locale) }}" method="post" enctype="multipart/form-data">
        @csrf

        <div class="container mt-5">

            <div class="">
                <select class="dropdown btn btn-warning" name="id" required>
                    <option class="dropdown-item" value="" selected disabled>Select Category</option>

                    @foreach($subCategories as $sub)
                        <option class="dropdown-item"
                                value="{{ $sub->id }}">{{ $sub->translate($locale)->name }}</option>
                    @endforeach
                </select>
            </div>


            <label for="productName" class="mt-4">{{ $attributes->translate($locale)->product_name }}</label>
            <input id="productName" name="productnameen" class="form-control mt-2" placeholder="English" required>
            <input id="productName" name="productnameka" class="form-control mt-2" placeholder="ქართულად" required>

            <label for="productDescription" class="mt-4">{{ $attributes->translate($locale)->product_description }}
                En</label>
            <textarea id="productDescription" name="productdescriptionen" class="form-control mt-2"
                      placeholder="English" required></textarea>
            <label for="productDescription" class="mt-4">{{ $attributes->translate($locale)->product_description }}
                Ge</label>
            <textarea id="productDescription" name="productdescriptionka" class="form-control mt-2"
                      placeholder="ქართულად" required></textarea>

            <label for="productStyle" class="mt-3">{{ $attributes->translate($locale)->style }}</label>
            <input id="productStyle" name="productstyleen" class="form-control mt-2" placeholder="English" required>
            <input id="productStyle" name="productstyleka" class="form-control mt-2" placeholder="ქართულად" required>

            <label for="productMaterial" class="mt-3">{{ $attributes->translate($locale)->material }}</label>
            <div class=" row container ">
                <select class=" form-control col-9">
                    <option value="" selected disabled>Select Material</option>
                    {{--                @foreach()--}}
                    <option value=""></option>
                    {{--                @endforeach--}}
                </select>
                <button class="btn btn-warning col-2 ml-4">Add Material in List</button>
            </div>

            <input id="productMaterial" name="productmaterialen" class="form-control mt-2" placeholder="English"
                   required>
            <input id="productMaterial" name="productmaterialka" class="form-control mt-2" placeholder="ქართულად"
                   required>

            <label for="productPrice" class="mt-3">{{ $attributes->translate($locale)->product_price }}</label>
            <input id="productPrice" name="price" class="form-control mt-2" placeholder="$" required>

            <div class="mt-3">
                <label
                    class=" mt-4">{{ $attributes->translate($locale)->product_image }}</label>
                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="inputGroupFileAddon01">Upload</span>
                    </div>
                    <div class="custom-file">
                        <input name="images[]" type="file" class="custom-file-input" id="inputGroupFile01"
                               aria-describedby="inputGroupFileAddon01" required multiple>
                        <label class="custom-file-label" for="inputGroupFile01">Choose file</label>
                    </div>
                </div>
            </div>
            <button type="submit" class="btn btn-primary mt-5">{{ $attributes->translate($locale)->create }}</button>
        </div>
    </form>
    @include('admin.layouts.footer')
@endsection

resources/views/admin/product/edit.blade.php
@extends('admin.layouts.app')
@section('content')
    @include('admin.layouts.header')

    @if($errors->all())
        <div class="notification error closeable">
            @foreach ($errors->all() as $error)
                <p>{{ $error }}</p>
            @endforeach
            <a class="close"></a>
        </div>
    @endif

    <form action="{{ route('product.update', [$locale, $product->id]) }}" method="post" enctype="multipart/form-data">
        @csrf
        @method('patch')
        <div class="container mt-3">

            <label class=" no-border  mt-4">{{ $attributes->translate($locale)->edit_product_name }}</label>
            <input class="form-control " name="productnameen" value="{{ $product->translate('en')->name }}">
            <input class="form-control mt-2" name="productnameka" value="{{ $product->translate('ka')->name }}">

            <label class=" no-border mt-4">{{ $attributes->translate($locale)->edit_product_description }}</label>
            <input class="form-control " name="descriptionen" value="{{ $product->translate('en')->description }}">
            <input class="form-control mt-2" name="descriptionka" value="{{ $product->translate('ka')->description }}">

            <label class=" no-border  mt-4">{{ $attributes->translate($locale)->edit_product_price }}</label>
            <input class="form-control " name="productprice" value="{{ $product->price }}">

            <div class="mt-3">
                <label
                    class=" mt-3">{{ $attributes->translate($locale)->edit_product_images }}</label>
                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="inputGroupFileAddon01">Upload</span>
                    </div>
                    <div class="custom-file">
                        <input name="image[]" type="file" class="custom-file-input" id="inputGroupFile01"
                               aria-describedby="inputGroupFileAddon01" multiple>
                        <label class="custom-file-label" for="inputGroupFile01">Choose file</label>
                    </div>
                </div>
            </div>
            @foreach($product->images as $one)
                <div class="form-group  mt-4 img-wrap ">
                    <span onclick="document.getElementById('remove-image').submit();" class="close x">&times;</span>
                    <img class="profile-pic" src="/images/products/{{ $one->image }}"/>

                </div>
            @endforeach
            <div class="container mb-lg-5 mt-lg-5">
                <button type="submit" class="btn btn-warning mt-2 mb-lg-5">{{ $attributes->translate($locale)->save_changes }}</button>
            </div>
        </div>
    </form>


        <form id="remove-image" action="{{ route('image.destroy', [  $locale, $one->id ?? '' ] ) }}" method="post">
            @csrf

            @method('delete')
        </form>

    @include('admin.layouts.footer')
@endsection

resources/views/admin/product/index.blade.php
@extends('admin.layouts.app')
@section('content')
    @include('admin.layouts.header')

    @if($errors->all())
        <div class="notification error closeable">
            @foreach ($errors->all() as $error)
                <p>{{ $error }}</p>
            @endforeach
            <a class="close"></a>
        </div>
    @endif
    <div class="container mt-3">

        <button onclick="window.location='{{ route("product.create", $locale) }}'"
                class="btn btn-primary mb-3">{{ $attributes->translate($locale)->create_product }}
        </button>

        <div class="container">
            <div class="card">
                <div class="card-header">
                    <span class="card-title">{{ $attributes->translate($locale)->products }}</span>
                </div>

                <div class="table-stats order-table ">
                    <table class="table">
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>{{ $attributes->translate($locale)->name }}</th>
                            <th>{{ $attributes->translate($locale)->createdAt }}</th>
                            <th></th>
                        </tr>
                        </thead>
                        @foreach($products as $product)

                            <form method="post" action="{{ route('product.destroy',[  $locale, $product->id]) }}">
                                @csrf
                                {{ method_field('delete') }}

                                <tbody>
                                <tr>

                                    <td>{{$product->id }}</td>
                                    <td>{{$product->translate($locale)->name}}</td>
                                    <td>{{$product->created_at}}</td>
                                    <td class="row pull-right mr-2">
                                        {{Form::open(['method' => 'post', 'route' => ['product.update',  $locale, $product->id] ])}}
                                        @csrf
                                        @method('patch')
                                        <button type="submit" value="{{ $product->id }}" name="favorite"
                                                class="mr-4"><span style='font-size:17px; font-weight: bold; color: {{ ($product->favorite == 1) ? '#d1d102' : '#1c1c0c' }} ; cursor: pointer'>&#9733;</span></button>
                                        {{ Form::close()  }}

                                    </td>
                                    <td class="row pull-right mr-2">

                                        {{Form::open(['method' => 'delete', 'route' => ['product.destroy',  $locale, $product->id] ])}}
                                        <button type="submit"
                                                class="btn btn-sm btn-danger delete mr-1">{{ $attributes->translate($locale)->delete }}
                                        </button>
                                        {{ Form::close()  }}
                                    </td>

                                    <td class="row pull-right mr-2">


                                        <a href="{{ route('product.edit', [ $locale, $product->id]) }}"
                                           class="btn btn-sm btn-warning mr-1">{{ $attributes->translate($locale)->edit }}</a>




                                    </td>
                                </tr>
                                </tbody>
                            </form>
                        @endforeach
                    </table>
                </div>
            </div>
        </div>
    </div>

    @include('admin.layouts.footer')
@endsection