routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Attribute;

use App\helper\ClearStream;
use App\Streamer;


Route::get('/', function () {


    $attributes = Attribute::first();
    $locale = app()->getLocale();
    $all = Streamer::all();

    if ($all->isEmpty()) {
        $first = 0;
    } else {

        if (Streamer::count() < 4) {
            $first = Streamer::latest()->first()->id;
        } else {
            $first = $all->first()->id;
        }

    }


    return redirect('home/en/' . $first)->with($locale, $attributes);
});

Route::get('/home', function () {
    $attributes = Attribute::first();
    $locale = app()->getLocale();
    $all = Streamer::all();

    if ($all->isEmpty()) {
        $first = 0;
    } else {

        if (Streamer::count() < 4) {
            $first = Streamer::latest()->first()->id;
        } else {
            $first = $all->first()->id;
        }

    }

    return redirect('home/en/' . $first)->with($locale, $attributes);
});

Route::get('/home/en', function () {
    $attributes = Attribute::first();
    $locale = app()->getLocale();
    $all = Streamer::all();

    if ($all->isEmpty()) {
        $first = 0;
    } else {

        if (Streamer::count() < 4) {

            $first = Streamer::latest()->first()->id;

        } else {
            $first = $all->first()->id;
        }

    }

    return redirect('home/en/' . $first)->with($locale, $attributes);
});

Route::get('/admin', function () {
    $attributes = Attribute::first();
    $locale = app()->getLocale();
    return redirect('admin/en')->with($locale, $attributes);
});


Auth::routes(['register' => false]);


Route::get('/home/{locale}/{forID}', 'HomeController@index')->name('home');
Route::get('/portfolio/{locale}', 'HomeController@portfolio')->name('portfolio');
Route::get('/about/{locale}', 'HomeController@about')->name('about');
Route::get('/contact/{locale}', 'HomeController@contact')->name('contact');


Route::get('createTranslate', 'HomeController@createTranslate')->name('createTranslate');


Route::post('destroyAll', 'adminControllers\ContactController@destroyAll')->name('destroyAll');


Route::middleware('auth')->prefix('admin/{locale}')->group(function () {


    Route::get('/', 'adminControllers\AdminController@index')->name('dashboard');

    Route::resource('category', 'adminControllers\CategoryController');
    Route::resource('sub-category', 'adminControllers\SubCategoryController');
    Route::resource('product', 'adminControllers\ProductController');
    Route::resource('attribute', 'adminControllers\AttributeController');
    Route::resource('contact', 'adminControllers\ContactController');
    Route::resource('image', 'adminControllers\ImageController');
    Route::resource('about', 'adminControllers\AboutController');
    Route::resource('info', 'adminControllers\InfoController');
    Route::resource('slide', 'adminControllers\SlideController');
    Route::resource('partner', 'adminControllers\PartnerController');

});


Route::get('/content/{locale}', 'HomeController@content')->name('content');
Route::post('/search/{locale}', 'HomeController@search')->name('search');
Route::post('/stream', 'HomeController@stream')->name('stream');
Route::get('/show/{locale}/{id}', 'HomeController@show')->name('show');
Route::get('/streaming/{locale}/{id}', 'HomeController@streaming')->name('streaming');
Route::get('/policy', 'HomeController@policy')->name('policy');
Route::get('/home/en/cleanStreams', 'HomeController@cleanStreams')->name('cleanStreams');
Route::get('/children', 'HomeController@children')->name('children');
Route::get('/info', 'HomeController@info')->name('info');
Route::get('/creature', 'HomeController@creature')->name('creature');
Route::get('/works', 'HomeController@works')->name('works');
Route::get('/testpage/{locale}/{id}', 'HomeController@testpage')->name('testpage');
Route::post('/jsDeleteStream/{id}', 'HomeController@jsDeleteStream')->name('jsDeleteStream');
Route::post('/checkIp', 'HomeController@checkIp')->name('checkIp');


Route::get('/testpage', function () {


    $attributes = Attribute::first();
    $locale = app()->getLocale();
    $all = Streamer::all();

    if ($all->isEmpty()) {
        $first = 0;
    } else {
        $first = $all->first()->id;
    }


    return redirect('testpage/en/' . $first)->with($locale, $attributes);
});

Route::get('/testpage/en', function () {
    $attributes = Attribute::first();
    $locale = app()->getLocale();
    $all = Streamer::all();

    if ($all->isEmpty()) {
        $first = 0;
    } else {
        $first = $all->first()->id;
    }

    return redirect('testpage/en/' . $first)->with($locale, $attributes);
});

resources/views/admin/messages/index.blade.php
@extends('admin.layouts.app')
@section('content')
    @include('admin.layouts.header')

    @if($errors->all())
        <div class="notification error closeable">
            @foreach ($errors->all() as $error)
                <p>{{ $error }}</p>
            @endforeach
            <a class="close"></a>
        </div>
    @endif

    <div class="container mt-3">

        <form action="{{ route("destroyAll", $locale) }}" method="post">
            @csrf
        <button onclick="window.location='{{ route("destroyAll", $locale) }}'" class="btn btn-primary mb-3">{{ $attributes->translate($locale)->clearAllMessages }}
        </button>
        </form>

        <div class="container">
            <div class="card">
                <div class="card-header">
                    <span class="card-title">{{ $attributes->translate($locale)->messages }}</span>
                </div>

                <div class="table-stats order-table ">
                    <table class="table">
                        <thead>
                        <tr>

                            <th>{{ $attributes->translate($locale)->name }}</th>
                            <th>{{ $attributes->translate($locale)->email }}</th>
                            <th>{{ $attributes->translate($locale)->description }}</th>
                            <th>{{ $attributes->translate($locale)->createdAt }}</th>
                            <th></th>
                        </tr>
                        </thead>
                        @foreach($messages as $one)

                            <form method="post" action="{{ route('contact.destroy',[  $locale, $one->id]) }}">
                                @csrf
                                {{ method_field('delete') }}
                                <tbody>
                                <tr>
                                    <td>{{$one->name}}</td>
                                    <td>{{$one->email}}</td>
                                    <td>{{Str::limit(strip_tags($one->description),15,'...')}}</td>
                                    <td>{{$one->created_at}}</td>
                                    <td class="row pull-right mr-2">
                                        <a href="{{ route('contact.show', [ $locale, $one->id]) }}"
                                           class="btn btn-sm btn-primary mr-1">Read</a>
                                        <button type="submit"
                                                class="btn btn-sm btn-danger delete">Delete</button>
                                    </td>
                                </tr>
                                </tbody>
                            </form>
                        @endforeach
                    </table>
                </div>


            </div>

        </div>


    </div>




    @include('admin.layouts.footer')
@endsection

resources/views/admin/messages/show.blade.php
@extends('admin.layouts.app')
@section('content')
    @include('admin.layouts.header')

    <div class="container mt-3">

        <div class="container">
            <div class="card">
                <div class="card-header">
                    <span class="form-control-label">Message from {{ $message->name }} on : {{ $message->created_at }} </span>
                </div>

                <div class="container">

                    <article class="articles mt-4">{{ $message->description }}</article>

                </div>


            </div>

        </div>

        <form action="{{ route("contact.destroy", [$locale, $message->id ]) }}" method="post">
            @csrf
            @method('delete')
            <button
                onclick="window.location='{{ route("contact.destroy", [$locale, $message->id ]) }}'"
                class="btn btn-primary mb-3 mr-4 pull-right">Delete
            </button>
        </form>
    </div>
    @include('admin.layouts.footer')
@endsection